MIN_TARGET_POWER_MW = 1.0
MAX_TARGET_POWER_MW = 100.0

POWER_RAMP_RATE_MW_PER_SECOND = 20.0
CURRENT_MA_PER_MW = 4.0
HEATING_RATE_C_PER_MW_SECOND = 0.005

AMBIENT_TEMPERATURE_C = 25.0
COOLING_RATE_C_PER_SECOND = 1.0

FAULT_TEMPERATURE_C = 60.0
MAX_SAFE_RECOVERY_TEMPERATURE_C = 45.0
FAULT_CURRENT_MA = 450.0
MAX_SAFE_RECOVERY_CURRENT_MA = 400.0
